apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: istio-system
spec:
  egress:
  - hosts:
    - "istio-system/*"
    - "monitoring/*"
    - "loki-stack/*"
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
